# Generated by Django 3.1.7 on 2021-04-06 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contactos', '0010_auto_20210317_2027'),
        ('Compras', '0007_auto_20210306_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('IGV', models.FloatField(default=0.18, verbose_name='IGV')),
                ('precioT', models.PositiveIntegerField(blank=True, default=0, verbose_name='Precio Total de la venta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contactos.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='detVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.PositiveIntegerField(blank=True, default='', verbose_name='Cantidad Producto')),
                ('precioU', models.PositiveIntegerField(blank=True, default=0, verbose_name='Precio Unitario')),
                ('precioT', models.PositiveIntegerField(blank=True, default=0, verbose_name='Precio Total')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compras.producto')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
                'db_table': 'detVent',
            },
        ),
    ]
