# Generated by Django 3.1.7 on 2021-04-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_auto_20210406_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detventa',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_detVent', to='Facturacion.venta'),
        ),
    ]
