# Generated by Django 3.1.7 on 2021-04-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testT',
        ),
    ]
