# Generated by Django 3.1.7 on 2021-02-23 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante')),
                ('estado', models.CharField(blank=True, default='', max_length=20, verbose_name='Estado Fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'fabricante',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre')),
                ('modelo', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('presentacion', models.CharField(blank=True, default='', max_length=100, verbose_name='Presentacion')),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, verbose_name='Descripcion')),
                ('estado', models.CharField(blank=True, default='', max_length=20, verbose_name='Estado Producto')),
                ('costo', models.FloatField(null=True, verbose_name='Costo')),
                ('Utilidad', models.FloatField(null=True, verbose_name='Utilidad')),
                ('precioVenta', models.FloatField(null=True, verbose_name='Precio de Venta')),
                ('stockIn', models.IntegerField(null=True, verbose_name='Stock Inicial')),
                ('imagen', models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Stock Inicial')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compras.fabricante')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
