# Generated by Django 3.1.7 on 2021-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_auto_20210223_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
