# Generated by Django 3.1.7 on 2021-03-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_auto_20210224_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Utilidad',
            new_name='utilidad',
        ),
    ]
