# Generated by Django 3.1.7 on 2021-04-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210416_2035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
