# Generated by Django 3.1.7 on 2021-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210416_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='user_permissions',
            new_name='permisos',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='rol',
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Descripcion Rol'),
            preserve_default=False,
        ),
    ]
