# Generated by Django 3.1.7 on 2021-04-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210417_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NombreCompleto',
            field=models.CharField(blank=True, max_length=120, verbose_name='nombre y apellido'),
        ),
    ]
