# Generated by Django 3.1.7 on 2021-03-04 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Contacto')),
                ('apellido', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido Contacto')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante')),
                ('estado', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Estado Fabricante')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Cliente')),
                ('sitioWeb', models.CharField(blank=True, default='', max_length=100, verbose_name='Sitio Web')),
                ('telefono', models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono')),
                ('calle', models.CharField(blank=True, default='', max_length=100, verbose_name='Calle')),
                ('ciudad', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('regionProvincia', models.CharField(blank=True, default='', max_length=100, verbose_name='Region/Provincia')),
                ('codPostal', models.CharField(blank=True, default='', max_length=100, verbose_name='Codigo Postal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contactos.contacto')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contactos.pais')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientees',
                'db_table': 'cliente',
            },
        ),
    ]
