# Generated by Django 3.1.7 on 2021-03-13 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0002_contacto_st'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombreCli',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codPostal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='regionProvincia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sitioWeb',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoCli',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='emailCli',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Email Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='st',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Estado Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefonoCli',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono Cliente'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellidoProv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailProv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Email Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombreProv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contactos.pais'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='st',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Estado Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefonoProv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono Proveedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
