# Generated by Django 3.1.7 on 2021-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0004_auto_20210312_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codPostal',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombreEmp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroImp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numero de Impuesto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regionProvincia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region/Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sitioWeb',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numero de Impuesto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefonoEmp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono Empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codPostal',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombreEmp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numeroImp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numero de Impuesto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regionProvincia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region/Provincia'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitioWeb',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numero de Impuesto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefonoEmp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telefono Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
