# Generated by Django 3.1.7 on 2021-03-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0007_auto_20210313_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Direccion'),
        ),
    ]
