# Generated by Django 3.1.7 on 2021-03-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0008_auto_20210313_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='calle',
        ),
    ]
