# Generated by Django 3.1.7 on 2021-03-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0009_auto_20210315_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='desc',
            new_name='descripcion',
        ),
    ]
